microservice-chart:
  namespace: "receipts"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-receipt-pdf-helpdesk
    tag: "0.9.4"
    pullPolicy: Always
  # https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/Controllers/HostController.cs
  livenessProbe:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 80 #http
    - 12345 #jmx-exporter
  service:
    type: ClusterIP
    ports:
      - 80 #http
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weuuat.receipts.internal.uat.platform.pagopa.it"
    path: /pagopa-receipt-pdf-helpdesk/(.*)
    servicePort: 80
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "768Mi"
      cpu: "300m"
    limits:
      memory: "1.5Gi"
      cpu: "500m"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
      - type: memory
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  fileConfig: {}
  envConfig:
    ENV: "uat"
    TZ: "Europe/Rome"
    WEBSITE_SITE_NAME: "pagopareceiptpdfhelpdesk" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    RECEIPT_QUEUE_TOPIC: "pagopa-u-weu-receipts-queue-receipt-waiting-4-gen"
    COSMOS_RECEIPT_SERVICE_ENDPOINT: "https://pagopa-u-weu-receipts-ds-cosmos-account.documents.azure.com:443/"
    COSMOS_BIZ_EVENT_SERVICE_ENDPOINT: "https://pagopa-u-weu-bizevents-ds-cosmos-account.documents.azure.com:443/"
    COSMOS_RECEIPT_DB_NAME: "db"
    COSMOS_BIZ_EVENT_DB_NAME: "db"
    COSMOS_RECEIPT_CONTAINER_NAME: "receipts"
    COSMOS_RECEIPT_ERROR_CONTAINER_NAME: "receipts-message-errors"
    COSMOS_RECEIPT_MESSAGE_CONTAINER_NAME: "receipts-io-messages"
    COSMOS_RECEIPT_CART_CONTAINER_NAME: "cart-for-receipts"
    COSMOS_BIZ_EVENT_CONTAINER_NAME: "biz-events"
    PDF_ENGINE_ENDPOINT: "https://api.uat.platform.pagopa.it/shared/pdf-engine/v1/generate-pdf"
    BLOB_STORAGE_ACCOUNT_ENDPOINT: "https://pagopauweureceiptsfnsa.blob.core.windows.net"
    BLOB_STORAGE_CONTAINER_NAME: "pagopa-u-weu-receipts-azure-blob-receipt-st-attach"
    WORKING_DIRECTORY_PATH: "/temp"
    PDV_TOKENIZER_BASE_PATH: "https://api.uat.tokenizer.pdv.pagopa.it/tokenizer/v1"
    PDV_TOKENIZER_INITIAL_INTERVAL: "200"
    PDV_TOKENIZER_MULTIPLIER: "2.0"
    PDV_TOKENIZER_RANDOMIZATION_FACTOR: "0.6"
    PDV_TOKENIZER_MAX_RETRIES: "3"
    ENABLE_ECS_CONSOLE: "true"
    CONSOLE_LOG_THRESHOLD: "DEBUG"
    CONSOLE_LOG_PATTERN: "%d{HH:mm:ss.SSS}[%thread]%-5level%logger{36}-%msg%n"
    CONSOLE_LOG_CHARSET: "UTF-8"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopareceiptpdfhelpdeskotl,deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    MAX_DATE_DIFF_MILLIS: "1800000" # 30min
    MAX_DATE_DIFF_NOTIFY_MILLIS: "1800000" # 30nin
    MAX_DATE_DIFF_CART_MILLIS: "1800000" # 30nin
    TRIGGER_NOTIFY_REC_SCHEDULE: "0 0 */1 * * *"
    RECOVER_FAILED_CRON: "0 0 */1 * * *"
    RECOVER_FAILED_CART_CRON: "0 0 */1 * * *"
    AZURE_FUNCTIONS_MESH_JAVA_OPTS: "-javaagent:/home/site/wwwroot/jmx_prometheus_javaagent-0.19.0.jar=12345:/home/site/wwwroot/config.yaml -javaagent:/home/site/wwwroot/opentelemetry-javaagent.jar -Xmx768m -XX:+UseG1GC"
    FAILED_AUTORECOVER_ENABLED: "true"
    NOT_NOTIFIED_AUTORECOVER_ENABLED: "true"
    FAILED_CART_AUTORECOVER_ENABLED: "false"
    RECOVER_FAILED_MASSIVE_MAX_DAYS: "1"
    RECOVER_NOT_NOTIFIED_MASSIVE_MAX_DAYS: "1"
    RECOVER_NOT_NOTIFIED_MASSIVE_MAX_RECORDS: "200"
  envConfigMapExternals:
    template-maps:
      BRAND_LOGO_MAP: brand-logo-map
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-u-connection-string"
    COSMOS_RECEIPTS_CONN_STRING: "cosmos-receipt-connection-string"
    RECEIPTS_STORAGE_CONN_STRING: "receipts-storage-account-connection-string"
    AzureWebJobsStorage: "receipts-storage-account-connection-string"
    COSMOS_BIZ_EVENT_CONN_STRING: "cosmos-biz-event-u-connection-string"
    COSMOS_RECEIPT_KEY: "cosmos-receipt-pkey"
    COSMOS_BIZ_EVENT_KEY: "cosmos-bizevent-pkey"
    OTEL_EXPORTER_OTLP_HEADERS: "elastic-otl-secret-token"
    PDV_TOKENIZER_SUBSCRIPTION_KEY: "tokenizer-api-key"
    OCP_APIM_SUBSCRIPTION_KEY: "shared-apim-u-subscription-key"
    AES_SECRET_KEY: "aes-secret-key"
    AES_SALT: "aes-salt"
  keyvault:
    name: "pagopa-u-receipts-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: false
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: false
    deployment:
      create: false
      image:
        repository: ghcr.io/pagopa/pagopa-receipt-pdf-helpdesk
        tag: "1.0.4"
        pullPolicy: Always
      envConfig:
      envSecret:
